{{- range $key, $value := .Values.services }}
{{ if hasKey $value "ports" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $key }}
  labels:
{{ include "artemis.labels" $ | indent 4 }}
spec:
  ports:
  {{- range $value.ports }}
  - name: {{ . | quote }}
    port: {{ . }}
    targetPort: {{ . }}
  {{- end }}
  selector:
    app: {{ $key }}
---
{{- end }}
{{- end }}
